//
// Created by lhy on 25-7-20.
//

#ifndef EVENTS_H
#define EVENTS_H

enum class MouseStatus {
  MOUSE_LEFT_UP,
  MOUSE_LEFT_DOWN,
  MOUSE_LEFT_MOVE,
  MOUSE_RIGHT_UP,
  MOUSE_RIGHT_DOWN,
  MOUSE_RIGHT_MOVE,
  MOUSE_MOVE,
  MOUSE_IDLE,
  MOUSE_LEFT_IDLE,
  MOUSE_RIGHT_IDLE
};
#endif  // EVENTS_H
